# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TCPIPTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serverUtilities
import threading

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(36, 169, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(36, 205, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(469, 166, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(35, 22, 717, 123))
        self.textEdit.setObjectName("textEdit")
        self.btnCustom = QtWidgets.QRadioButton(self.centralwidget)
        self.btnCustom.setGeometry(QtCore.QRect(579, 169, 95, 20))
        self.btnCustom.setObjectName("btnCustom")
        self.btnOption2 = QtWidgets.QRadioButton(self.centralwidget)
        self.btnOption2.setGeometry(QtCore.QRect(580, 192, 95, 20))
        self.btnOption2.setObjectName("btnOption2")
        self.btnOption3 = QtWidgets.QRadioButton(self.centralwidget)
        self.btnOption3.setGeometry(QtCore.QRect(580, 216, 106, 20))
        self.btnOption3.setObjectName("btnOption3")
        self.btnOption4 = QtWidgets.QRadioButton(self.centralwidget)
        self.btnOption4.setGeometry(QtCore.QRect(580, 239, 189, 20))
        self.btnOption4.setObjectName("btnOption4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.start_server)
        self.pushButton_2.clicked.connect(self.print_values)
        self.pushButton_3.clicked.connect(self.send_data)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def start_server(self):
        serverUtilities.establish_connection()

    def print_values(self):
        print('')
        print(serverUtilities.conn)
        print(serverUtilities.addr)

    def send_data(self):
        if self.btnCustom.isChecked():
            str_data = self.textEdit.toPlainText()
            list_data = str_data.split(" ")
            temp_tuple = ()
            send_data = []
            i = 0
            for str_num in list_data:
                int_num = int(str_num)
                if i == 1:
                    i = 0
                    temp_tuple = temp_tuple + (int_num, )
                    send_data.append(temp_tuple)
                    temp_tuple = ()
                else:
                    temp_tuple = temp_tuple + (int_num, )
                    i += 1

        if self.btnOption2.isChecked():
            send_data = []
        if self.btnOption3.isChecked():
            send_data = [(1, 2), (3, 4)]
        if self.btnOption4.isChecked():
            send_data = [(1, 2), (3, 4), (5, 6)]

        thread = threading.Thread(target=serverUtilities.send_data_thread, args=[send_data])
        thread.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Server Demo"))
        self.pushButton.setText(_translate("MainWindow", "Start Server"))
        self.pushButton_2.setText(_translate("MainWindow", "Conn / Addr"))
        self.pushButton_3.setText(_translate("MainWindow", "Send"))
        self.btnCustom.setText(_translate("MainWindow", "Custom"))
        self.btnOption2.setText(_translate("MainWindow", "[]"))
        self.btnOption3.setText(_translate("MainWindow", "[(1,2), (3,4)]"))
        self.btnOption4.setText(_translate("MainWindow", "[(1,2),(3,4),(5,6)]"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
